In [75]:
import pandas as pd
import numpy as np
import tensorflow as tf
import re

In [76]:
games_df = pd.read_csv("../Resources/vgsales.csv.zip")
ratings_df = pd.read_csv("../Resources/metacritic_games.csv")

In [77]:
games_df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [78]:
ratings_df.rename({"game":"Name"},axis=1, inplace=True)
ratings_df

,Name,platform,developer,genre,number_players,rating,release_date,positive_critics,neutral_critics,negative_critics,positive_users,neutral_users,negative_users,metascore,user_score
0,Portal 2,PC,Valve Software,Action,NaN,E10+,"Apr 18, 2011",51,1,0,1700,107,19,95,90
1,The Elder Scrolls V: Skyrim,PC,Bethesda Game Studios,Role-Playing,No Online Multiplayer,M,"Nov 10, 2011",32,0,0,1616,322,451,94,82
2,The Legend of Zelda: Ocarina of Time 3D,3DS,GREZZO,Miscellaneous,No Online Multiplayer,E10+,"Jun 19, 2011",84,1,0,283,20,5,94,90
3,Batman: Arkham City,PC,Rocksteady Studios,Action Adventure,NaN,T,"Nov 21, 2011",27,0,0,240,34,27,91,87
4,Super Mario 3D Land,3DS,Nintendo,Action,No Online Multiplayer,E,"Nov 13, 2011",81,1,0,251,39,11,90,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5694,Modern Combat: Blackout,Switch,Gameloft,Action,No Online Multiplayer,NaN,"Feb 14, 2019",0,5,2,1,0,1,53,57
5695,Fimbul,PS4,Zaxis,Action Adventure,No Online Multiplayer,NaN,"Feb 28, 2019",0,7,2,1,0,0,52,18
5696,Generation Zero,PC,Avalanche Studios,Action Adventure,Online Multiplayer,T,"Mar 26, 2019",1,11,6,5,2,6,50,57
5697,Vane,PS4,Friend & Foe,Adventure,No Online Multiplayer,E10+,"Jan 15, 2019",3,26,22,2,2,2,49,55
5698,Left Alive,PS4,"Square Enix, ilinx inc.",Action Adventure,No Online Multiplayer,M,"Mar 5, 2019",1,7,27,25,8,21,37,79

In [61]:
combo_df = pd.merge(games_df, ratings_df, on="Name", how="inner")

In [62]:
# Not enough crossover
combo_df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,...,rating,release_date,positive_critics,neutral_critics,negative_critics,positive_users,neutral_users,negative_users,metascore,user_score
0,17,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,...,M,"Nov 18, 2014",14,0,0,114,15,13,97,78
1,17,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,...,M,"Nov 18, 2014",66,0,0,369,71,69,97,83
2,17,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,...,M,"Apr 14, 2015",56,1,0,407,108,250,96,77
3,24,Grand Theft Auto V,X360,2013.0,Action,Take-Two Interactive,9.63,5.31,0.06,1.38,...,M,"Nov 18, 2014",14,0,0,114,15,13,97,78
4,24,Grand Theft Auto V,X360,2013.0,Action,Take-Two Interactive,9.63,5.31,0.06,1.38,...,M,"Nov 18, 2014",66,0,0,369,71,69,97,83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2587,16475,Azure Striker Gunvolt: Striker Pack,3DS,2016.0,Action,Inti Creates,0.00,0.00,0.01,0.00,...,T,"Aug 31, 2017",8,1,0,3,1,1,82,75
2588,16568,Teslagrad,PSV,2015.0,Platform,Rain Games,0.00,0.01,0.00,0.00,...,E,"Dec 13, 2013",12,3,0,12,8,0,77,77
2589,16568,Teslagrad,PSV,2015.0,Platform,Rain Games,0.00,0.01,0.00,0.00,...,E,"Sep 11, 2014",11,4,0,3,3,0,79,81
2590,16568,Teslagrad,PSV,2015.0,Platform,Rain Games,0.00,0.01,0.00,0.00,...,E,"Apr 14, 2015",10,4,0,6,6,3,78,67
2591,16568,Teslagrad,PSV,2015.0,Platform,Rain Games,0.00,0.01,0.00,0.00,...,E,"Dec 7, 2017",6,2,0,3,0,0,81,78

In [63]:
games_list = games_df["Name"].values.tolist()
ratings_list = ratings_df["Name"].values.tolist()
print(len(games_list))
print(len(ratings_list))

16598
5699

In [67]:
g_standardized_titles=[]
for game in games_list:
    x = re.compile("\W|\s")
    edited_title= re.sub(x,"-", game).lower().replace("--","-")
    if edited_title[-1] == "-":
        edited_title = edited_title[:-1]
    g_standardized_titles.append(edited_title)

In [68]:
r_standardized_titles=[]
for game in ratings_list:
    x = re.compile("\W|\s")
    edited_title= re.sub(x,"-", game).lower().replace("--","-")
    if edited_title[-1] == "-":
        edited_title = edited_title[:-1]
    r_standardized_titles.append(edited_title)

In [69]:
print(len(g_standardized_titles))
print(len(r_standardized_titles))

16598
5699

In [70]:
for game in g_standardized_titles:
    if game in r_standardized_titles:
        g_standardized_titles.remove(game)
        r_standardized_titles.remove(game)
    else:
        continue

In [73]:
len(g_standardized_titles)

15574

In [74]:
len(r_standardized_titles)

4675